# Generated by Django 5.2.5 on 2025-08-29 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='likes',
        ),
        migrations.AddField(
            model_name='quote',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
