# Generated by Django 5.2.5 on 2025-08-29 16:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0003_viewhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='quotes_app.quote'),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['source', 'weight'], name='quotes_app__source_de87d3_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['views'], name='quotes_app__views_23d703_idx'),
        ),
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['session_key', 'quote'], name='quotes_app__session_30b9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['viewed_at'], name='quotes_app__viewed__6b8ea1_idx'),
        ),
    ]
