# Generated by Django 5.2.5 on 2025-08-30 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0004_alter_quote_source_alter_quote_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quote',
            name='quotes_app__source_de87d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='quote',
            name='quotes_app__views_23d703_idx',
        ),
        migrations.RemoveIndex(
            model_name='viewhistory',
            name='quotes_app__session_30b9ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='viewhistory',
            name='quotes_app__viewed__6b8ea1_idx',
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes_app.quote'),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
